/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--snow-canvas)',
        card: 'var(--snow-card)',
        'snow-2': 'var(--snow-2)',
        'snow-3': 'var(--snow-3)',
        hairline: 'var(--hairline)',
        'hairline-bold': 'var(--hairline-bold)',
        ink: 'var(--ink)',
        'ink-2': 'var(--ink-2)',
        'ink-3': 'var(--ink-3)',
        'ink-4': 'var(--ink-4)',
        cobalt: {
          50: 'var(--cobalt-50)',
          100: 'var(--cobalt-100)',
          200: 'var(--cobalt-200)',
          300: 'var(--cobalt-300)',
          400: 'var(--cobalt-400)',
          500: 'var(--cobalt-500)',
          600: 'var(--cobalt-600)',
          700: 'var(--cobalt-700)',
          800: 'var(--cobalt-800)',
          900: 'var(--cobalt-900)',
          950: 'var(--cobalt-950)',
        },
        glacier: {
          300: 'var(--glacier-300)',
          500: 'var(--glacier-500)',
          700: 'var(--glacier-700)',
        },
        brass: {
          300: 'var(--brass-300)',
          500: 'var(--brass-500)',
          700: 'var(--brass-700)',
        },
        positive: 'var(--positive)',
        'positive-wash': 'var(--positive-wash)',
        caution: 'var(--caution)',
        'caution-wash': 'var(--caution-wash)',
        negative: 'var(--negative)',
        'negative-wash': 'var(--negative-wash)',
        midnight: 'var(--midnight)',
        'midnight-card': 'var(--midnight-card)',
        'midnight-ink': 'var(--midnight-ink)',
        'midnight-ink-2': 'var(--midnight-ink-2)',
        'midnight-line': 'var(--midnight-line)',
      },
      fontFamily: {
        serif: 'var(--font-serif)',
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        'display-1': 'var(--text-display-1)',
        'display-2': 'var(--text-display-2)',
        'display-3': 'var(--text-display-3)',
        title: 'var(--text-title)',
        subtitle: 'var(--text-subtitle)',
        lede: 'var(--text-lede)',
        body: 'var(--text-body)',
        'body-app': 'var(--text-body-app)',
        small: 'var(--text-small)',
        micro: 'var(--text-micro)',
        'metric-lg': 'var(--text-metric-lg)',
        eyebrow: 'var(--text-eyebrow)',
      },
      borderRadius: {
        controls: '10px',
        containers: '16px',
        stage: '24px',
        identity: '999px',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        cta: 'var(--shadow-cta)',
      },
      transitionDuration: {
        'dur-1': 'var(--dur-1)',
        'dur-2': 'var(--dur-2)',
        'dur-3': 'var(--dur-3)',
        'dur-4': 'var(--dur-4)',
        'dur-5': 'var(--dur-5)',
      },
      transitionTimingFunction: {
        'ease-out': 'var(--ease-out)',
        'ease-cinema': 'var(--ease-cinema)',
        'ease-inout': 'var(--ease-inout)',
        'ease-spring': 'var(--ease-spring)',
      }
    },
  },
  plugins: [],
}
